#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dodoc"
name = "do•doc"
description.en = "Documentation tool for creativity"
description.fr = "Documentation tool for creativity"

version = "9.1.2~ynh1"

maintainers = ["johndoe"]

[upstream]
license = "AGPL-3.0-only"
website = "https://latelier-des-chercheurs.fr/"
demo = "https://test.dodoc.fr/"
admindoc = "https://forum.latelier-des-chercheurs.fr/t/installer-do-doc-en-ligne/210"
code = "https://github.com/l-atelier-des-chercheurs/dodoc"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/dodoc"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/l-atelier-des-chercheurs/dodoc/archive/refs/tags/v9.1.2.tar.gz"
        sha256 = "1f6a31667bb6940a6f78fd9924796e518bbe05e87ec48e78b0d7602cfc5e0289"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "ffmpeg libx11-xcb1 libxcomposite1 libxi6 libxext6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0"
